//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domains.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDomains {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDomains() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domains.Resources.ResDomains", typeof(ResDomains).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string lbFacebook {
            get {
                return ResourceManager.GetString("lbFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string lbFirstName {
            get {
                return ResourceManager.GetString("lbFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        public static string lbLastName {
            get {
                return ResourceManager.GetString("lbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lbMobile {
            get {
                return ResourceManager.GetString("lbMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string lbWebsite {
            get {
                return ResourceManager.GetString("lbWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغيير كلمة المرور.
        /// </summary>
        public static string MsgChangeFail {
            get {
                return ResourceManager.GetString("MsgChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string MsgChangesuccess {
            get {
                return ResourceManager.GetString("MsgChangesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدثت مشكلة اثناء الحفظ.
        /// </summary>
        public static string MsgSavedError {
            get {
                return ResourceManager.GetString("MsgSavedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الحفظ.
        /// </summary>
        public static string MsgSavedFailed {
            get {
                return ResourceManager.GetString("MsgSavedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string MsgSavedSuccessfully {
            get {
                return ResourceManager.GetString("MsgSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال العنوان.
        /// </summary>
        public static string vMsgAddressReq {
            get {
                return ResourceManager.GetString("vMsgAddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار الوسيلة الاعلانيه.
        /// </summary>
        public static string vMsgAdsMethodReq {
            get {
                return ResourceManager.GetString("vMsgAdsMethodReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الاجابة.
        /// </summary>
        public static string vMsgAnswerReq {
            get {
                return ResourceManager.GetString("vMsgAnswerReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم عربي.
        /// </summary>
        public static string vMsgArNameReq {
            get {
                return ResourceManager.GetString("vMsgArNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم الطريقة عربي.
        /// </summary>
        public static string vMsgArPaymentReq {
            get {
                return ResourceManager.GetString("vMsgArPaymentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الوصف القصير عربي.
        /// </summary>
        public static string vMsgArShortDesReq {
            get {
                return ResourceManager.GetString("vMsgArShortDesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار مقال.
        /// </summary>
        public static string vMsgArticleReq {
            get {
                return ResourceManager.GetString("vMsgArticleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال العنوان عربي.
        /// </summary>
        public static string vMsgArTitleReq {
            get {
                return ResourceManager.GetString("vMsgArTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال محتوى الرسالة.
        /// </summary>
        public static string vMsgBodyReq {
            get {
                return ResourceManager.GetString("vMsgBodyReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال سعر الحجز.
        /// </summary>
        public static string vMsgBookingPriceReq {
            get {
                return ResourceManager.GetString("vMsgBookingPriceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد القسم.
        /// </summary>
        public static string vMsgCategoryReq {
            get {
                return ResourceManager.GetString("vMsgCategoryReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رابط القناة.
        /// </summary>
        public static string vMsgChannelLinkReq {
            get {
                return ResourceManager.GetString("vMsgChannelLinkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال كود الكورس.
        /// </summary>
        public static string vMsgCodeReq {
            get {
                return ResourceManager.GetString("vMsgCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر كورس.
        /// </summary>
        public static string vMsgCourseReq {
            get {
                return ResourceManager.GetString("vMsgCourseReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار نوع الكورس.
        /// </summary>
        public static string vMsgCourseTypeReq {
            get {
                return ResourceManager.GetString("vMsgCourseTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب القسم يجب ان يكون رقم صحيح.
        /// </summary>
        public static string vMsgDepartmentOrderint {
            get {
                return ResourceManager.GetString("vMsgDepartmentOrderint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ترتيب القسم.
        /// </summary>
        public static string vMsgDepartmentOrderReq {
            get {
                return ResourceManager.GetString("vMsgDepartmentOrderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف عربي.
        /// </summary>
        public static string vMsgDescriptionArReq {
            get {
                return ResourceManager.GetString("vMsgDescriptionArReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف انجليزي.
        /// </summary>
        public static string vMsgDescriptionEnReq {
            get {
                return ResourceManager.GetString("vMsgDescriptionEnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف.
        /// </summary>
        public static string vMsgDescriptionReq {
            get {
                return ResourceManager.GetString("vMsgDescriptionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال قيمة الخصم.
        /// </summary>
        public static string vMsgDisountReq {
            get {
                return ResourceManager.GetString("vMsgDisountReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني مسجل من قبل.
        /// </summary>
        public static string vMsgEmailExist {
            get {
                return ResourceManager.GetString("vMsgEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل بريد الكتروني صحيح.
        /// </summary>
        public static string vMsgEmailIncorrect {
            get {
                return ResourceManager.GetString("vMsgEmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string vMsgEmailNotCorrect {
            get {
                return ResourceManager.GetString("vMsgEmailNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال البريد الالكتروني.
        /// </summary>
        public static string vMsgEmailReq {
            get {
                return ResourceManager.GetString("vMsgEmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم إنجليزي.
        /// </summary>
        public static string vMsgEnNameReq {
            get {
                return ResourceManager.GetString("vMsgEnNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال اسم الطريقة انجليزي.
        /// </summary>
        public static string vMsgEnPaymentReq {
            get {
                return ResourceManager.GetString("vMsgEnPaymentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الوصف القصير إنجليزي.
        /// </summary>
        public static string vMsgEnShortDesReq {
            get {
                return ResourceManager.GetString("vMsgEnShortDesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل مبلغ صحيح.
        /// </summary>
        public static string vMsgEnterCorrectAmount {
            get {
                return ResourceManager.GetString("vMsgEnterCorrectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال العنوان إنجليزي.
        /// </summary>
        public static string vMsgEnTitleReq {
            get {
                return ResourceManager.GetString("vMsgEnTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الفيس بوك.
        /// </summary>
        public static string vMsgFacebookReq {
            get {
                return ResourceManager.GetString("vMsgFacebookReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الميزة عربي مطلوب.
        /// </summary>
        public static string vMsgFeatureTextArReq {
            get {
                return ResourceManager.GetString("vMsgFeatureTextArReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الميزة انجليزي مطلوب.
        /// </summary>
        public static string vMsgFeatureTextEnReq {
            get {
                return ResourceManager.GetString("vMsgFeatureTextEnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء اختيار ملف.
        /// </summary>
        public static string vMsgfileReq {
            get {
                return ResourceManager.GetString("vMsgfileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم الاول.
        /// </summary>
        public static string vMsgFristNameReq {
            get {
                return ResourceManager.GetString("vMsgFristNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الاسم.
        /// </summary>
        public static string vMsgFullNameReq {
            get {
                return ResourceManager.GetString("vMsgFullNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال جوجل بلس.
        /// </summary>
        public static string vMsgGooglePlusReq {
            get {
                return ResourceManager.GetString("vMsgGooglePlusReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار ايقونة.
        /// </summary>
        public static string vMsgIconReq {
            get {
                return ResourceManager.GetString("vMsgIconReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ترتيب الصورة.
        /// </summary>
        public static string vMsgImageOrderReq {
            get {
                return ResourceManager.GetString("vMsgImageOrderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار صورة.
        /// </summary>
        public static string vMsgImagePathReq {
            get {
                return ResourceManager.GetString("vMsgImagePathReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار صورة.
        /// </summary>
        public static string vMsgImageReq {
            get {
                return ResourceManager.GetString("vMsgImageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار صورة.
        /// </summary>
        public static string vMsgImageReq1 {
            get {
                return ResourceManager.GetString("vMsgImageReq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار صور.
        /// </summary>
        public static string vMsgImagesReq {
            get {
                return ResourceManager.GetString("vMsgImagesReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال وصف الصورة عربي.
        /// </summary>
        public static string vMsgImageTextArReq {
            get {
                return ResourceManager.GetString("vMsgImageTextArReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال وصف الصورة انجليزي.
        /// </summary>
        public static string vMsgImageTextEnReq {
            get {
                return ResourceManager.GetString("vMsgImageTextEnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ميلاد غير صحيح.
        /// </summary>
        public static string vMsgIncorrectDate {
            get {
                return ResourceManager.GetString("vMsgIncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال انستجرام.
        /// </summary>
        public static string vMsgInstagramReq {
            get {
                return ResourceManager.GetString("vMsgInstagramReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فصلك اختر درجة الاهتمام.
        /// </summary>
        public static string vMsgInterestDegreeReq {
            get {
                return ResourceManager.GetString("vMsgInterestDegreeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الملف غير صحيح يسمح باختيار صورة فقط.
        /// </summary>
        public static string vMsgInvalidImage {
            get {
                return ResourceManager.GetString("vMsgInvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم الاخير.
        /// </summary>
        public static string vMsgLastNameReq {
            get {
                return ResourceManager.GetString("vMsgLastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر العميل.
        /// </summary>
        public static string vMsgLeadReq {
            get {
                return ResourceManager.GetString("vMsgLeadReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال لينكد ان.
        /// </summary>
        public static string vMsgLinkedinReq {
            get {
                return ResourceManager.GetString("vMsgLinkedinReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال الرابط.
        /// </summary>
        public static string vMsgLinkReq {
            get {
                return ResourceManager.GetString("vMsgLinkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رابط العنوان.
        /// </summary>
        public static string vMsgLocationUrlReq {
            get {
                return ResourceManager.GetString("vMsgLocationUrlReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار لوجو.
        /// </summary>
        public static string vMsgLogoReq {
            get {
                return ResourceManager.GetString("vMsgLogoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال فديو الصفحى الرئيسية.
        /// </summary>
        public static string vMsgMainVideoReq {
            get {
                return ResourceManager.GetString("vMsgMainVideoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى لعدد الحروف 100.
        /// </summary>
        public static string vMsgMaxLength100 {
            get {
                return ResourceManager.GetString("vMsgMaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى لعدد الحروف هو 150 حرف.
        /// </summary>
        public static string vMsgMaxLength150 {
            get {
                return ResourceManager.GetString("vMsgMaxLength150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصي لعدد الحروف 200.
        /// </summary>
        public static string vMsgMaxLength200 {
            get {
                return ResourceManager.GetString("vMsgMaxLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى المسموح به للرابط هو 250 حرف.
        /// </summary>
        public static string vMsgMaxLength250 {
            get {
                return ResourceManager.GetString("vMsgMaxLength250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى 300 حرف.
        /// </summary>
        public static string vMsgMaxLength300 {
            get {
                return ResourceManager.GetString("vMsgMaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصي لعدد الحروف 50.
        /// </summary>
        public static string vMsgMaxLength50 {
            get {
                return ResourceManager.GetString("vMsgMaxLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى لعدد الحروف 500 حرف.
        /// </summary>
        public static string vMsgMaxLength500 {
            get {
                return ResourceManager.GetString("vMsgMaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الاقصى لعدد الحروف 600 حرف.
        /// </summary>
        public static string vMsgMaxLength600 {
            get {
                return ResourceManager.GetString("vMsgMaxLength600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار نوع الملف.
        /// </summary>
        public static string vMsgMediaTypeReq {
            get {
                return ResourceManager.GetString("vMsgMediaTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال نص الرسالة.
        /// </summary>
        public static string vMsgMessageReq {
            get {
                return ResourceManager.GetString("vMsgMessageReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال وصف محرك البحث.
        /// </summary>
        public static string vMsgMetaDescriptionReq {
            get {
                return ResourceManager.GetString("vMsgMetaDescriptionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الكلمات الدلالية.
        /// </summary>
        public static string vMsgMetaTagsReq {
            get {
                return ResourceManager.GetString("vMsgMetaTagsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخل رقم التليفون.
        /// </summary>
        public static string vMsgMobileReq {
            get {
                return ResourceManager.GetString("vMsgMobileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار الوحده.
        /// </summary>
        public static string vMsgModuleReq {
            get {
                return ResourceManager.GetString("vMsgModuleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإسم .
        /// </summary>
        public static string vMsgNameReq {
            get {
                return ResourceManager.GetString("vMsgNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح باستخدام المسافة فى اسم المستخدم.
        /// </summary>
        public static string vMsgNoSpace {
            get {
                return ResourceManager.GetString("vMsgNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الترتيب.
        /// </summary>
        public static string vMsgOrderReq {
            get {
                return ResourceManager.GetString("vMsgOrderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال ترتيب الفقرة.
        /// </summary>
        public static string vMsgParagraphReq {
            get {
                return ResourceManager.GetString("vMsgParagraphReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب الا تقل عن 6 احرف ولا تزيد عن 50 حرف.
        /// </summary>
        public static string vMsgPasswordRange {
            get {
                return ResourceManager.GetString("vMsgPasswordRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال كلمة المرور.
        /// </summary>
        public static string vMsgPasswordReq {
            get {
                return ResourceManager.GetString("vMsgPasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال مسار او رابط الملف.
        /// </summary>
        public static string vMsgPathOrLinkReq {
            get {
                return ResourceManager.GetString("vMsgPathOrLinkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رابط الدفع.
        /// </summary>
        public static string vMsgPaymentLinkReq {
            get {
                return ResourceManager.GetString("vMsgPaymentLinkReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر الصلاحيات.
        /// </summary>
        public static string vMsgPermissionReq {
            get {
                return ResourceManager.GetString("vMsgPermissionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب الصفحه يجب ان يكون رقم صحيح.
        /// </summary>
        public static string vMsgPgeOrderint {
            get {
                return ResourceManager.GetString("vMsgPgeOrderint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ترتيب الصفحة.
        /// </summary>
        public static string vMsgPgeOrderReq {
            get {
                return ResourceManager.GetString("vMsgPgeOrderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التليفون مسجل بالفعل.
        /// </summary>
        public static string vMsgPhoneExists {
            get {
                return ResourceManager.GetString("vMsgPhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم هاتف غير صحيح.
        /// </summary>
        public static string vMsgPhoneIncorrect {
            get {
                return ResourceManager.GetString("vMsgPhoneIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار مشغل الفديو.
        /// </summary>
        public static string vMsgPlayerReq {
            get {
                return ResourceManager.GetString("vMsgPlayerReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال السعر.
        /// </summary>
        public static string vMsgPriceReq {
            get {
                return ResourceManager.GetString("vMsgPriceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال السؤال.
        /// </summary>
        public static string vMsgQuestionReq {
            get {
                return ResourceManager.GetString("vMsgQuestionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر تقييم.
        /// </summary>
        public static string vMsgRateReq {
            get {
                return ResourceManager.GetString("vMsgRateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف القصير عربي.
        /// </summary>
        public static string vMsgShortDescriptionArReq {
            get {
                return ResourceManager.GetString("vMsgShortDescriptionArReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف القصير انجليزي.
        /// </summary>
        public static string vMsgShortDescriptionEnReq {
            get {
                return ResourceManager.GetString("vMsgShortDescriptionEnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال الوصف القصير.
        /// </summary>
        public static string vMsgShortDescriptionReq {
            get {
                return ResourceManager.GetString("vMsgShortDescriptionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الموقع عربي.
        /// </summary>
        public static string vMsgSiteNameArReq {
            get {
                return ResourceManager.GetString("vMsgSiteNameArReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الموقع انجليزي.
        /// </summary>
        public static string vMsgSiteNameEnReq {
            get {
                return ResourceManager.GetString("vMsgSiteNameEnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الموقع.
        /// </summary>
        public static string vMsgSiteNameReq {
            get {
                return ResourceManager.GetString("vMsgSiteNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال سناب شات.
        /// </summary>
        public static string vMsgSnapchatReq {
            get {
                return ResourceManager.GetString("vMsgSnapchatReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ساوند كلاود.
        /// </summary>
        public static string vMsgSoundCloudReq {
            get {
                return ResourceManager.GetString("vMsgSoundCloudReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال العنوان.
        /// </summary>
        public static string vMsgTitleReq {
            get {
                return ResourceManager.GetString("vMsgTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل تاريخ الاتصال.
        /// </summary>
        public static string vMsgTrackingDateReq {
            get {
                return ResourceManager.GetString("vMsgTrackingDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال تويتر.
        /// </summary>
        public static string vMsgTwitterReq {
            get {
                return ResourceManager.GetString("vMsgTwitterReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إختيار النوع.
        /// </summary>
        public static string vMsgTypeReq {
            get {
                return ResourceManager.GetString("vMsgTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل رابط صحيح.
        /// </summary>
        public static string vMsgUrlIncorrect {
            get {
                return ResourceManager.GetString("vMsgUrlIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك اختر المجموعة.
        /// </summary>
        public static string vMsgUserGroupReq {
            get {
                return ResourceManager.GetString("vMsgUserGroupReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود بالفعل.
        /// </summary>
        public static string vMsgUserNameExists {
            get {
                return ResourceManager.GetString("vMsgUserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم يجب الا يقل عن 6 احرف.
        /// </summary>
        public static string vMsgUserNameMustBe6 {
            get {
                return ResourceManager.GetString("vMsgUserNameMustBe6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم يجب ان يحتوى على حروف انجليزية وارقام وان يبدا بحرف.
        /// </summary>
        public static string vMsgUserNameMustContainsLettersAndNums {
            get {
                return ResourceManager.GetString("vMsgUserNameMustContainsLettersAndNums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم يجب ان يبدأ بحرف.
        /// </summary>
        public static string vMsgUserNameMustStartWithLetter {
            get {
                return ResourceManager.GetString("vMsgUserNameMustStartWithLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم المستخدم.
        /// </summary>
        public static string vMsgUserNameReq {
            get {
                return ResourceManager.GetString("vMsgUserNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم الواتس.
        /// </summary>
        public static string vMsgWhatsAppReq {
            get {
                return ResourceManager.GetString("vMsgWhatsAppReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رابط يوتيوب.
        /// </summary>
        public static string vMsgYoutubeReq {
            get {
                return ResourceManager.GetString("vMsgYoutubeReq", resourceCulture);
            }
        }
    }
}
