//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipAssistProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebsite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebsite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VipAssistProject.Resources.ResWebsite", typeof(ResWebsite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur.
        /// </summary>
        public static string lbAbout {
            get {
                return ResourceManager.GetString("lbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos de nous.
        /// </summary>
        public static string lbAbout_Us {
            get {
                return ResourceManager.GetString("lbAbout Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à propos de AccoladeConciergerie.
        /// </summary>
        public static string lbaboutAccolade {
            get {
                return ResourceManager.GetString("lbaboutAccolade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        public static string lbAddress {
            get {
                return ResourceManager.GetString("lbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un service global de conciergerie aéroportuaire,.
        /// </summary>
        public static string lbAglobalairport {
            get {
                return ResourceManager.GetString("lbAglobalairport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les agents d&apos;aéroport sont des opérateurs de sociétés de manutention certifiés et ont accès à toutes les zones aéroportuaires, y compris côté piste, garantissant une efficacité maximale dans toutes les procédures aéroportuaires..
        /// </summary>
        public static string lbAirport {
            get {
                return ResourceManager.GetString("lbAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aéroport.
        /// </summary>
        public static string lbAirpot {
            get {
                return ResourceManager.GetString("lbAirpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez déjà un compte?.
        /// </summary>
        public static string lbAlready_have_an_account_ {
            get {
                return ResourceManager.GetString("lbAlready have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et plus.
        /// </summary>
        public static string lbAnd_More {
            get {
                return ResourceManager.GetString("lbAnd More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sac Quantité.
        /// </summary>
        public static string lbBagQty {
            get {
                return ResourceManager.GetString("lbBagQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve maintenant.
        /// </summary>
        public static string lbBook_Now {
            get {
                return ResourceManager.GetString("lbBook Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réserver un tiers.
        /// </summary>
        public static string lbBookThirdParty {
            get {
                return ResourceManager.GetString("lbBookThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donner vie à votre idée de.
        /// </summary>
        public static string lbBringing {
            get {
                return ResourceManager.GetString("lbBringing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petit chariot.
        /// </summary>
        public static string lbBuggy {
            get {
                return ResourceManager.GetString("lbBuggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construire.
        /// </summary>
        public static string lbBuild {
            get {
                return ResourceManager.GetString("lbBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entreprise.
        /// </summary>
        public static string lbBusiness {
            get {
                return ResourceManager.GetString("lbBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la voiture.
        /// </summary>
        public static string lbCarName {
            get {
                return ResourceManager.GetString("lbCarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chariot.
        /// </summary>
        public static string lbCart {
            get {
                return ResourceManager.GetString("lbCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier.
        /// </summary>
        public static string lbCheckout {
            get {
                return ResourceManager.GetString("lbCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disent les clients.
        /// </summary>
        public static string lbClient_Say {
            get {
                return ResourceManager.GetString("lbClient Say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102 / 5000
        ///Translation results
        ///Remplissez le formulaire ci-dessous pour recevoir un e-mail avec le code d&apos;autorisation nécessaire pour réinitialiser votre mot de passe..
        /// </summary>
        public static string lbComplete_the_form_below_to_receive_an_email_with_the_authorization_code_needed_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("lbComplete the form below to receive an email with the authorization code needed " +
                        "to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous contacter.
        /// </summary>
        public static string lbContact_Us {
            get {
                return ResourceManager.GetString("lbContact Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string lbCreate {
            get {
                return ResourceManager.GetString("lbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expérience client..
        /// </summary>
        public static string lbcustomer_experience {
            get {
                return ResourceManager.GetString("lbcustomer experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Développer.
        /// </summary>
        public static string lbDevelop {
            get {
                return ResourceManager.GetString("lbDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string lbDocuments {
            get {
                return ResourceManager.GetString("lbDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas encore de compte? S&apos;INSCRIRE.
        /// </summary>
        public static string lbDon_t_have_an_account_yet__SIGN_UP {
            get {
                return ResourceManager.GetString("lbDon\'t have an account yet? SIGN UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse e-mail.
        /// </summary>
        public static string lbEmail_address {
            get {
                return ResourceManager.GetString("lbEmail address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lbEnglish {
            get {
                return ResourceManager.GetString("lbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surtout.
        /// </summary>
        public static string lbespecially {
            get {
                return ResourceManager.GetString("lbespecially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to excitée.
        /// </summary>
        public static string lbexcited {
            get {
                return ResourceManager.GetString("lbexcited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exclusif et.
        /// </summary>
        public static string lbExclusiveand {
            get {
                return ResourceManager.GetString("lbExclusiveand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extrêmement.
        /// </summary>
        public static string lbextremely {
            get {
                return ResourceManager.GetString("lbextremely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string lbFaq {
            get {
                return ResourceManager.GetString("lbFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès rapide au confort de votre salon d&apos;avion en buggy électrique..
        /// </summary>
        public static string lbFastTrack {
            get {
                return ResourceManager.GetString("lbFastTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fonctionnalités.
        /// </summary>
        public static string lbFeatures {
            get {
                return ResourceManager.GetString("lbFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N&apos;hésitez pas à demander des détails, ne gardez aucune question !.
        /// </summary>
        public static string lbFeel_free_to_ask_for_details__don_t_save_any_questions_ {
            get {
                return ResourceManager.GetString("lbFeel free to ask for details, don\'t save any questions!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de vol.
        /// </summary>
        public static string lbFlightDate {
            get {
                return ResourceManager.GetString("lbFlightDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du vol.
        /// </summary>
        public static string lbFlightName {
            get {
                return ResourceManager.GetString("lbFlightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;état du vol.
        /// </summary>
        public static string lbFlightStatus {
            get {
                return ResourceManager.GetString("lbFlightStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oubliée.
        /// </summary>
        public static string lbForgot {
            get {
                return ResourceManager.GetString("lbForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le français.
        /// </summary>
        public static string lbFrench {
            get {
                return ResourceManager.GetString("lbFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquemment demandé.
        /// </summary>
        public static string lbFrequentlyAsked {
            get {
                return ResourceManager.GetString("lbFrequentlyAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom et prénom.
        /// </summary>
        public static string lbFull_Name {
            get {
                return ResourceManager.GetString("lbFull Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrer en .
        /// </summary>
        public static string lbGet_In {
            get {
                return ResourceManager.GetString("lbGet In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrer en contact.
        /// </summary>
        public static string lbGet_In_Touch {
            get {
                return ResourceManager.GetString("lbGet In Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencez maintenant.
        /// </summary>
        public static string lbGetStartedNow {
            get {
                return ResourceManager.GetString("lbGetStartedNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saluer.
        /// </summary>
        public static string lbGreet {
            get {
                return ResourceManager.GetString("lbGreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les salutations.
        /// </summary>
        public static string lbGreetings {
            get {
                return ResourceManager.GetString("lbGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heureuse.
        /// </summary>
        public static string lbhappy {
            get {
                return ResourceManager.GetString("lbhappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients heureux.
        /// </summary>
        public static string lbHappy_Clients {
            get {
                return ResourceManager.GetString("lbHappy Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string lbHome {
            get {
                return ResourceManager.GetString("lbHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les heures.
        /// </summary>
        public static string lbHours {
            get {
                return ResourceManager.GetString("lbHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incroyablement.
        /// </summary>
        public static string lbincredibly {
            get {
                return ResourceManager.GetString("lbincredibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bébé Quantité.
        /// </summary>
        public static string lbInfantQty {
            get {
                return ResourceManager.GetString("lbInfantQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grande base d&apos;entreprise sur 6 continents.
        /// </summary>
        public static string lblarge {
            get {
                return ResourceManager.GetString("lblarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniers.
        /// </summary>
        public static string lbLatest {
            get {
                return ResourceManager.GetString("lbLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apprendre encore plus.
        /// </summary>
        public static string lbLearn_More {
            get {
                return ResourceManager.GetString("lbLearn More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat de la vie.
        /// </summary>
        public static string lbLifeChat {
            get {
                return ResourceManager.GetString("lbLifeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacemets.
        /// </summary>
        public static string lbLocations {
            get {
                return ResourceManager.GetString("lbLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connexion.
        /// </summary>
        public static string lbLog_In {
            get {
                return ResourceManager.GetString("lbLog In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string lbLog_Out {
            get {
                return ResourceManager.GetString("lbLog Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOT DE PASSE PERDU?.
        /// </summary>
        public static string lbLOST_YOUR_PASSWORD_ {
            get {
                return ResourceManager.GetString("lbLOST YOUR PASSWORD?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voyage luxueux !.
        /// </summary>
        public static string lbluxurioustravel_ {
            get {
                return ResourceManager.GetString("lbluxurioustravel!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service de conciergerie de luxe basé à Londres avec une large clientèle à travers le monde..
        /// </summary>
        public static string lbLuxury {
            get {
                return ResourceManager.GetString("lbLuxury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service de rencontre et d&apos;accueil.
        /// </summary>
        public static string lbMeet {
            get {
                return ResourceManager.GetString("lbMeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rencontrer.
        /// </summary>
        public static string lbMeetName {
            get {
                return ResourceManager.GetString("lbMeetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un message.
        /// </summary>
        public static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes commandes.
        /// </summary>
        public static string lbMy_Orders {
            get {
                return ResourceManager.GetString("lbMy Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil.
        /// </summary>
        public static string lbMy_Profile {
            get {
                return ResourceManager.GetString("lbMy Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée n&apos;est disponible.
        /// </summary>
        public static string lbNoDataAvailable {
            get {
                return ResourceManager.GetString("lbNoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureau.
        /// </summary>
        public static string lbOffice {
            get {
                return ResourceManager.GetString("lbOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commande terminée.
        /// </summary>
        public static string lbOrder_Complete {
            get {
                return ResourceManager.GetString("lbOrder Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos.
        /// </summary>
        public static string lbOur {
            get {
                return ResourceManager.GetString("lbOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos clients.
        /// </summary>
        public static string lbOur_Clients {
            get {
                return ResourceManager.GetString("lbOur Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTRE MISSION.
        /// </summary>
        public static string lbOUR_MISSION {
            get {
                return ResourceManager.GetString("lbOUR MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre équipe est prête à vous aider 24h/24 et 7j/7 pour toutes vos questions, pour vous assurer de passer un moment sans stress à l&apos;aéroport. Veuillez nous contacter pour discuter de vos besoins spécifiques en matière d&apos;aéroport..
        /// </summary>
        public static string lbOur_teamis {
            get {
                return ResourceManager.GetString("lbOur teamis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTRE VISION.
        /// </summary>
        public static string lbOUR_VISION {
            get {
                return ResourceManager.GetString("lbOUR VISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notre équipe s&apos;occupera de tout pendant que vous vous détendez..
        /// </summary>
        public static string lbOurteam {
            get {
                return ResourceManager.GetString("lbOurteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus de 1000 clients dans 100 pays utilisent les services AccoladeConcierge. Rencontrez nos clients..
        /// </summary>
        public static string lbOver1000 {
            get {
                return ResourceManager.GetString("lbOver1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string lbPages {
            get {
                return ResourceManager.GetString("lbPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to méthodes de payement.
        /// </summary>
        public static string lbPayment_Methods {
            get {
                return ResourceManager.GetString("lbPayment Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personne Quantité.
        /// </summary>
        public static string lbPersonQty {
            get {
                return ResourceManager.GetString("lbPersonQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string lbPhone {
            get {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passer la commande.
        /// </summary>
        public static string lbPlaceOrder {
            get {
                return ResourceManager.GetString("lbPlaceOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir le sujet..
        /// </summary>
        public static string lbPlease_enter_the_subject_ {
            get {
                return ResourceManager.GetString("lbPlease enter the subject.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir votre adresse e-mail..
        /// </summary>
        public static string lbPlease_enter_your_email_address_ {
            get {
                return ResourceManager.GetString("lbPlease enter your email address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir votre message..
        /// </summary>
        public static string lbPlease_enter_your_message_ {
            get {
                return ResourceManager.GetString("lbPlease enter your message.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;il vous plaît entrez votre nom..
        /// </summary>
        public static string lbPlease_enter_your_name_ {
            get {
                return ResourceManager.GetString("lbPlease enter your name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string lbPosts {
            get {
                return ResourceManager.GetString("lbPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string lbPrice {
            get {
                return ResourceManager.GetString("lbPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos données personnelles seront utilisées pour soutenir votre expérience tout au long de ce site Web, pour gérer l&apos;accès à votre compte et à d&apos;autres fins décrites dans notre.
        /// </summary>
        public static string lbPrivacy {
            get {
                return ResourceManager.GetString("lbPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to politique de confidentialité..
        /// </summary>
        public static string lbprivacy_policy_ {
            get {
                return ResourceManager.GetString("lbprivacy policy.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procéder à.
        /// </summary>
        public static string lbProceed_to {
            get {
                return ResourceManager.GetString("lbProceed to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        public static string lbProduct {
            get {
                return ResourceManager.GetString("lbProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string lbQuantity {
            get {
                return ResourceManager.GetString("lbQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des questions.
        /// </summary>
        public static string lbQuestions {
            get {
                return ResourceManager.GetString("lbQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souviens-toi de moi.
        /// </summary>
        public static string lbRemember_Me {
            get {
                return ResourceManager.GetString("lbRemember Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to demandes prises.
        /// </summary>
        public static string lbrequeststaken {
            get {
                return ResourceManager.GetString("lbrequeststaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser mon mot de passe.
        /// </summary>
        public static string lbReset_My_Password {
            get {
                return ResourceManager.GetString("lbReset My Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utilisateurs satisfaits, AccoladeConcierge est un énorme succès dans l&apos;une des plus grandes MarketPlace du monde.
        /// </summary>
        public static string lbSatisfied {
            get {
                return ResourceManager.GetString("lbSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer le message.
        /// </summary>
        public static string lbSend_Message {
            get {
                return ResourceManager.GetString("lbSend Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string lbServices {
            get {
                return ResourceManager.GetString("lbServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panier.
        /// </summary>
        public static string lbShopping_Cart {
            get {
                return ResourceManager.GetString("lbShopping Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s&apos;identifier.
        /// </summary>
        public static string lbSign_In {
            get {
                return ResourceManager.GetString("lbSign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string lbSolutions {
            get {
                return ResourceManager.GetString("lbSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sujette.
        /// </summary>
        public static string lbSubject {
            get {
                return ResourceManager.GetString("lbSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lbSubtotal {
            get {
                return ResourceManager.GetString("lbSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultez nos témoignages clients. ... Voici ce qu&apos;ils disent de nous..
        /// </summary>
        public static string lbTestimonials {
            get {
                return ResourceManager.GetString("lbTestimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;EXPÉRIENCE ULTIME À L&apos;AÉROPORT.
        /// </summary>
        public static string lbTHE {
            get {
                return ResourceManager.GetString("lbTHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le Total.
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string lbTouch {
            get {
                return ResourceManager.GetString("lbTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string lbTransportation {
            get {
                return ResourceManager.GetString("lbTransportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus de.
        /// </summary>
        public static string lbTrusted {
            get {
                return ResourceManager.GetString("lbTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string lbUsername {
            get {
                return ResourceManager.GetString("lbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir le panier.
        /// </summary>
        public static string lbView_Cart {
            get {
                return ResourceManager.GetString("lbView Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir plus.
        /// </summary>
        public static string lbView_More {
            get {
                return ResourceManager.GetString("lbView More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbVip côté piste et côté trottoir.
        /// </summary>
        public static string lbVipair {
            get {
                return ResourceManager.GetString("lbVipair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nous sommes.
        /// </summary>
        public static string lbWe_Are {
            get {
                return ResourceManager.GetString("lbWe Are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous ne sommes pas les seuls.
        /// </summary>
        public static string lbWe_renot {
            get {
                return ResourceManager.GetString("lbWe\'renot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous fournissons à nos clients un portefeuille de services sans compromis, nos différents services sont mis en œuvre avec soin pour s&apos;assurer que tous les désirs de nos clients sont satisfaits..
        /// </summary>
        public static string lbWeprovide {
            get {
                return ResourceManager.GetString("lbWeprovide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUBLIEZ LES PLANS DE VOYAGE STRESSANTS ET LAISSEZ-NOUS GUIDER VOTRE EXPÉRIENCE VIP. DU DÉPART À L&apos;ARRIVÉE NOTRE ÉQUIPE DÉDIÉE RENDRA VOTRE EXPÉRIENCE LA PLUS LISSE POSSIBLE..
        /// </summary>
        public static string lbWeProvide2 {
            get {
                return ResourceManager.GetString("lbWeProvide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous nous spécialisons dans tous les besoins de voyage, de style de vie et de loisirs à Londres, tout en veillant à maintenir la plus haute qualité de service en gérant vos besoins de transport sous l&apos;égide du groupe..
        /// </summary>
        public static string lbWespecialise {
            get {
                return ResourceManager.GetString("lbWespecialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous sommes AccoladeConcierge, Nous.
        /// </summary>
        public static string lbWeWe {
            get {
                return ResourceManager.GetString("lbWeWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce que.
        /// </summary>
        public static string lbWhat {
            get {
                return ResourceManager.GetString("lbWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui.
        /// </summary>
        public static string lbWho {
            get {
                return ResourceManager.GetString("lbWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POURQUOI NOUS.
        /// </summary>
        public static string lbWHY_US {
            get {
                return ResourceManager.GetString("lbWHY US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ans d&apos;activité.
        /// </summary>
        public static string lbYearsInBusiness {
            get {
                return ResourceManager.GetString("lbYearsInBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message nous a été envoyé..
        /// </summary>
        public static string lbYour_message_has_been_sent_to_us_ {
            get {
                return ResourceManager.GetString("lbYour message has been sent to us.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre commande.
        /// </summary>
        public static string lbYour_Order {
            get {
                return ResourceManager.GetString("lbYour Order", resourceCulture);
            }
        }
    }
}
